### ISSUE TITLE
Integrate IRI cluster with IF Kubernetes deployment

### ISSUE THREAD

**Issue by akashgoswami** [iotaledger/iri-regression#15]
The `create_cluster.py` needs to integrate with IF internal Kubernetes cluster to run integration tests. 

- [x] Obtain kube configuration from @geminoz.
- [ ] Setup kube configuration as part of secure storage BuildKite pipeline @geminoz . 
- [ ] `create_cluster.py` script should use kube configuration provided by BuildKite.

**Comment by geminoz** [comment]
This is in progress

- k8s cluster in place and kubectl configuration settled
- Buildkite agents ready to pull iri-regression and pipeline stored in iotaledger/ci-pipelines (private repo for now, likely opened tomorrow)

to do:
- setting up secure storage of secrets 
- then changing the pipeline.yml to actually invoke the create_cluster.py
