### ISSUE TITLE
Add performance testing 

### ISSUE THREAD

**Issue by DyrellC** [iotaledger/iri-regression#16]
###Description:
Write a set of performance testing in the dynamic testing features in each machine. The first will be `getTransactionsToApprove`, and the call duration will need to be logged in the dynamic test results directory in each machine. 

###Motivation:
We need to start up a framework for performance testing and ensure that they are running correctly on the kubernetes cluster.

###Requirements:
- [x] Have gTTA spammed on a synced node
- [x] Log resulting transactions and duration's 
 
Open Questions:
-What other metrics do we want to gather using the performance testing

**Comment by jakubcech** [comment]
What's the status of this? :)
