### ISSUE TITLE
Checksum Validation of snapshot.txt and db.tar

### ISSUE THREAD

**Issue by GalRogozinski** [iotaledger/iri-regression#2]
Description:
In `config.yml` we want to write the checksums of `snaphot.txt` and `db.tar` so we can verify they have the content we expect.

Motivation:
Will allow us to quickly identify why tests fail if something happens to those files.

Open Questions:
Who will be responsible for the validation? The regression code? The CI pipeline? Both?

**E: 3**

**Comment by DyrellC** [comment]
@karimodm This is done correct? If so, @jakubcech  we can close this

**Comment by karimodm** [comment]
The checksum validation is performed against the entire db.tar file before extracting and running IRI. The tar file should include the snapshot file as well, so the checksum will check everything as a result.
