### ISSUE TITLE
Correct Directory Structure

### ISSUE THREAD

**Issue by GalRogozinski** [iotaledger/iri-regression#3]
*Description/Motivation/Requirement:*
We need a project structure that will enable us to segregate feature tests and will be compliant with the way aloe loads modules. Aloe scans features and step files that can be found in *packages* under the feature directory.

Example of a directory structure should be:
```
- tests
  - features
    - machine1
       - first.feature
       - second.feature
     - machine2
        - another.feature
     - steps
        - step_category_a   #optional. Maybe add later when we have many steps 
          - first_step.py
          - another_step.py
 ```
*Each folder should also have an __init.py__ file.

In order for the CI pipeline to run the `machine1` features it should use the following command:
`$: find machine1/ -type f -name "*.feature" | sort | aloe`
We use `sort` in order to make sure that the tests are always run in a certain order.

*Open Questions*
Perhaps the features should be perfixed with numbers to enforce order?

**E: 5**

**Comment by DyrellC** [comment]
Using the `-w` flag in aloe lets you specify the working directory that the commands will be conducted in. This allows you to run aloe in each machine directory, and the setup will use the `output.yml` file from that specific directory when running the tests

**Comment by GalRogozinski** [comment]
Even though `-w` is shorter than `--where`, people who will be reviewing the code who are not familiar with `nose` won't know what it means. Since we will be writing this only once in a bash script I prefer `--where`

**Comment by DyrellC** [comment]
@jakubcech This is complete now, we can close this
