### ISSUE TITLE
Feature file - Stitching a non-solid sidetangle

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/iri-regression#30]
### Description
Extend the feature files so that we cover a scenario for stitching a non-solid sidetangle to the main tangle. 

The stitching transaction doesn't crash (on a 4GB and 4Core machine) the node when we do checkConsistency and checkSolidity (tight loop over analyzedHashes), and doesn't get confirmed. Adding a transaction that references the stitching transaction directly, that also doesn't crash. Static DB with a large sidetangle from the Mainnet. 

### Motivation
Cover the possibility of a node crashing when doing checkSolidity and checkConsistency on a large sidetangle 

### Issues
1. A node doing checkConsistency/checkSolidity on a large side tangle crashed. 
2. A transaction directly referencing a stitching transaction crashed. 

### How to test for this
1. Use an actual database (#sidetanglerocks) where we have a non-solid side tangle with lots of (invalid and valid two separate scenarios) transactions (e.g., incorrent spending TX with unbalanced output). The side tangle isn't stitched to the main tangle.
2. Set up on a node on a 4GB and 4Core, use the testnet flag and still use the mainnet coordinator and snapshot file.  
3. Create a stitching transaction

**Comment by DyrellC** [comment]
@jakubcech This is done already. See https://github.com/iotaledger/iri-regression/pull/42. This can be closed.
