### ISSUE TITLE
Each machine (pipeline) directory should have a setup feature

### ISSUE THREAD

**Issue by GalRogozinski** [iotaledger/iri-regression#4]
*Description*:
Each machine (pipeline) folder will need to have a unique feature file called `1_setup.feature`.
It will always run first and it will set up global environments.

*Motivation*:
We need to parse the `config.yml` file before we start the tests in order to know how to communicate with the nodes.

*Requirements*:
It should look like this
```
Feature: Set up global environment for tests

	Scenario: Configure machine 1
		Given node configuration "./tests/machine1/config.yml" 
		Then set up global environment
```

**E: 2**

**Comment by DyrellC** [comment]
The @before.all hook works exactly as intended, we won't need a separate configuration method for each machine. The path to the machine config yaml can be included in the `api_test_steps.py` file in the `yamlPaths` list for each new machine created for testing and the configuration method will handle mapping the machines and their respective nodes.
