### ISSUE TITLE
Global variables should reset between tests 

### ISSUE THREAD

**Issue by DyrellC** [iotaledger/iri-regression#41]
### Description
We need to clear out the global variables between tests. Each feature should be running on a clean slate to make sure that the nodes being used in the test, and any responses associated with them, are the correct ones for that feature/scenario. 

### Motivation
Ensure that all tests are running with the correct variables. This will eliminate the possibility that an incorrect configuration or response variable is injected into the wrong test. 

### Requirements
Add an `after` hook to the test steps to tear down any global variables for the next test.

### Open Questions (optional)
**1.** Is it reasonable to have the variables reset after each scenario rather than each feature?
**1a.** If this is the case what needs to change with the previous tests to make this work? 

### Am I planning to do it myself with a PR?
Yes

**Comment by GalRogozinski** [comment]
After each scenario is fine

**Comment by DyrellC** [comment]
This was done with https://github.com/iotaledger/iri-regression/pull/50
